# Generated by Django 4.1.1 on 2022-10-04 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 4, 16, 1, 17, 189891))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('folowers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('folows', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auto_catalog.post')),
            ],
        ),
    ]
