# Generated by Django 4.1.1 on 2022-10-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
