# Generated by Django 4.1.1 on 2022-10-04 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_catalog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 16, 3, 55, 689460)),
        ),
    ]
